### ISSUE TITLE
Search function not working

### ISSUE THREAD

**Issue by alwatud** [MaxBo/REPAiR-Web#275]
![image](https://user-images.githubusercontent.com/31543755/39824741-5c906e2a-53b0-11e8-8fd6-4476792ebc09.png)

Search for Actor doesn't show results.

**Comment by ChrFr** [comment]
issue was caused by a bug in the plugin used for the tables (django-rest-framework-datatables. i already informed  the author and he fixed this. The plugin on the server still had the old version though but should be up to date now. 
Thanks for the notification!
