### ISSUE TITLE
Page becomes unresponsive

### ISSUE THREAD

**Issue by rusne** [MaxBo/REPAiR-Web#415]
<img width="846" alt="region capture 1" src="https://user-images.githubusercontent.com/12959109/45811140-9d1bdf80-bccc-11e8-8c96-83fb0697b9ee.png">

After choosing a different than default activity for searching actors in the "Edit Actors" tab, the page becomes unresponsive and crashes.

**Comment by ChrFr** [comment]
Thanks for noting! I will look into it

**Comment by ChrFr** [comment]
seems to occur specially at this activity I-5610

**Comment by ChrFr** [comment]
actually it's not bugged, it just takes forever (6000+ actors)
trying to improve performance

**Comment by rusne** [comment]
maybe that's why every actor that I had to find was in this one activity :)
