### ISSUE TITLE
Is this repository maintained?

### ISSUE THREAD

**Issue by MPParsley** [MaxBo/REPAiR-Web#682]
Currently evaluating this project so this is a kind request to identify whether this repository, or any fork of this project, is maintained.

**Comment by MaxBo** [comment]
Dear @MPParsley ,
the repository is currently not maintained by us, as the Repair-Project in which this repo waas developed, finished last year.
See h2020repair.eu for further details.
However, the Startup geofluxus (see https://www.geofluxus.com ) uses and develops part of the codebase further. Please contact  
Rusne Sileryte @rusne for further information.

Best regards,

Max Bohnet
